shortest test7.po again
clang says:
error: string literal of length 71893
exceeds maximum length 65536 that C++ compilers are required
to support [-Werror,-Woverlength-strings]